### ISSUE TITLE
Wabbajack Even More Recipes Sanity check error

### ISSUE THREAD

**Issue by zerotheglitch** [Patchier/In-the-Stardew-of-the-Valley#5]
It seems that Wabbajack has a problem with installing Even More recipes since whenever i try to install the mod pack when it reaches the final mod which is the one aforementioned it will say it will extract up till the point it says the vacuuming is completed then immediately after it will give a sanity check error for the mod stating that it has "0 results, expecting 2" and I'm not sure if this is part of the error or just the Wabbajack mod manager but when i check the mods folder afterwards there's no folder or file afterwards where the extraction should have been placed.
[Wabbajack.current.log](https://github.com/Patchier/In-the-Stardew-of-the-Valley/files/6175913/Wabbajack.current.log)

**Comment by Patchier** [comment]
Zero, this issue happens when the system language is set to certain things besides English (typically Japanese). Please set to English during the install process.

**Comment by zerotheglitch** [comment]
thanks

**Comment by zerotheglitch** [comment]
I don't think it was the system language but the system locale in this case but that may not be true I still have to test I though once my computer reboots

**Comment by zerotheglitch** [comment]
it was the system locale in this case
